### PR TITLE
[fix] OSS/Lightning compatibility

### PR DESCRIPTION
**Pull request by blefaudeux**
# Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by blefaudeux** [comment]
see https://fb.workplace.com/groups/pytorchLightning/permalink/1403343693335498/?comment_id=1403478649988669 (internal FB)

**Comment by blefaudeux** [comment]
offending part in Lightning is https://github.com/PyTorchLightning/pytorch-lightning/blob/f4cc7451a94010a572480c43ad5f0af7ad52cd21/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L188

**Review by SeanNaren — APPROVED** [review]
Thanks @blefaudeux :)

**Review by min-xu-ai — COMMENTED** [review]
nice, unit test?

**Comment by blefaudeux** [comment]
> nice, unit test?

on the lightning side ? I don't think that it was really broken before, but I can add a check for that if you'd like

**Comment by min-xu-ai** [comment]
I thought this is a behavior we want to ensure for lightning. If so, a unit test in our code to ensure it is not broken in the future would be nice.

**Comment by blefaudeux** [comment]
I would argue that the lightning part is a bit broken around that, but ok, adding a unit test (more like a compliance test or something) later today

**Comment by blefaudeux** [comment]
> I would argue that the lightning part is a bit broken around that, but ok, adding a unit test (more like a compliance test or something) later today

done in #512

**Pull request merged**
