### PR TITLE
do not user worker for distributed pipeline

### PR DESCRIPTION
**Pull request by mrzzd**

### CODE REVIEW

**Comment by tmarkstrum** [comment]
Could you please add description to it?

**Comment by anj-s** [comment]
cc  @pbelevich  @SciPioneer

**Comment by min-xu-ai** [comment]
@anj-s @tmarkstrum I am closing this since this is not applicable anymore IMHO. Please reopen if I am mistaken.

**Comment by anj-s** [comment]
I wanted to cc the new owner of this work before closing this PR. I'll reopen, cc the owner and then close it.

**Comment by anj-s** [comment]
@pritamdamania87 @mrshenli @jamesr66a I wanted to highlight work that @mrzzd had completed in case it is relevant for the team. We are closing this PR for now.

**Pull request closed without merging**
