### PR TITLE
[fix] SDP syncing buffers during gradient accumulation

### LINKED ISSUE #1041: SDP sync_buffers() during gradient accumulation
Shouldn't [`sync_buffers()`](https://github.com/facebookresearch/fairscale/blob/fd7b962f7ae01b7f6ffbcdb31b4b53297174a645/fairscale/nn/data_parallel/sharded_ddp.py#L224) be guarded by [`_should_accumulate_grads()` just like reduce()](https://github.com/facebookresearch/fairscale/blob/fd7b962f7ae01b7f6ffbcdb31b4b53297174a645/fairscale/nn/data_parallel/sharded_ddp.py#L415)?

I think the current code is broadcasting buffers even in `no_sync()`.

### PR DESCRIPTION
**Pull request by blefaudeux**
## What does this PR do?
Fixes #1041. I just had a minute or two, hoping that it's enough :)

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/main/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [ ] N/A
- [x] Did you write any new necessary tests?
  - [ ] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/main/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by blefaudeux** [comment]
cc @min-xu-ai

**Review by min-xu-ai — APPROVED** [review]
lgtm！

**Comment by blefaudeux** [comment]
I've not followed the CI changes on Fairscale @min-xu-ai, looks like the breakages are not related (but they do touch OSS) but are pytorch version dependent ?

**Comment by min-xu-ai** [comment]
I trigged a rerun. The cpu test failure seems unrelated. But the GPU test failure seems to be in OSS?
```
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/circleci/fairscale/tests/optim/test_oss.py", line 956, in run_ddp_parity
    check_optimizer_equivalence(opt, change_train_graph=change_train_graph)
  File "/home/circleci/fairscale/tests/optim/test_oss.py", line 947, in check_optimizer_equivalence
    check_step()
  File "/home/circleci/fairscale/tests/optim/test_oss.py", line 912, in check_step
    loss_sharded_optim = cast(torch.Tensor, sharded_optimizer.step(closure=closure_sharded))
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/fairscale/fairscale/optim/oss.py", line 232, in step
    loss = self.optim.step(closure=closure, **kwargs)  # type: ignore
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/optim/adam.py", line 157, in step
    adam(params_with_grad,
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/optim/adam.py", line 213, in adam
    func(params,
  File "/home/circleci/venv/lib/python3.9/site-packages/torch/optim/adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.
change_train_graph = True, backend = 'nccl', broadcast_fp16 = False
```

**Comment by min-xu-ai** [comment]
it is interesting, all the failures seem to be the same. What the best way for me to run your branch? Do I git remote add your repo & branch?

**Comment by ruanslv** [comment]
These OSS tests are failing in the main branch (and in other unrelated PRs too). Agree that it's probably related to recent pytorch upgrade as I don't remember them failing last week.

I'm seeing all failures from here in a FSDP PR (https://github.com/facebookresearch/fairscale/pull/1052), including the CPU and the "test_parity3d_checkpoint_syncbn" ones.

**Comment by min-xu-ai** [comment]
somehow this PR hitting unrelated test errors. I am replacing it with: https://github.com/facebookresearch/fairscale/pull/1075

Thanks Ben!

**Pull request closed without merging**
