### PR TITLE
[docs] Remove style arg from tutorial_pipe_multiprocess.py

### PR DESCRIPTION
**Pull request by vfdev-5**
Update example as style arg was removed in https://github.com/facebookresearch/fairscale/pull/345

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by min-xu-ai** [comment]
oops, there is bug uncovered here in the CI script. Let me fix that first. @vfdev-5, do you mind merge master after and let CI rerun? Sorry about the inconvenience.

**Comment by vfdev-5** [comment]
@min-xu-ai thanks for the update and mention in CI fixing PR! I can merge the master here once it is fixed, no problems.

I wonder also if it worth mentioning that there are few other failures I found with `benchmark/pipe.py`. As it is not a public example, it can be acceptable that it can fail for some configs, but maybe worth get a comprehensible error message.

For example, if run as `python benchmarks/pipe.py --debug --ddp-zero` it hangs with the error about DP missing group:
```
>   Traceback (most recent call last):
  File "benchmarks/pipe.py", line 548, in <module>
    benchmark_single_process(args)
  File "benchmarks/pipe.py", line 450, in benchmark_single_process
    benchmark_language_model(model_config, pipe_model, benchmark_config, model_specs, args)
  File "benchmarks/pipe.py", line 326, in benchmark_language_model
    wps, loss = train(model_config, model, benchmark_config, model_specs, args)
  File "benchmarks/pipe.py", line 155, in train
    optimizer = optimizer(model.parameters())
  File "benchmarks/pipe.py", line 52, in make_adam
    return OSS(params=params, optim=Adam, group=get_data_parallel_group(), lr=lr)
  File "/fs-examples/fairscale/nn/model_parallel/initialize.py", line 134, in get_data_parallel_group
    assert _DATA_PARALLEL_GROUP is not None, "data parallel group is not initialized"
AssertionError: data parallel group is not initialized
```

if run as `python benchmarks/pipe.py --debug --ddp-zero --multiprocess`, it goes further but fails with
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/fs-examples/benchmarks/pipe.py", line 512, in benchmark_multiprocess
    run_mp_worker(args, world_size)
  File "/fs-examples/benchmarks/pipe.py", line 461, in run_mp_worker
    pipe_model = MultiProcessPipe(
  File "/fs-examples/fairscale/nn/pipe/multiprocess_pipe.py", line 215, in __init__
    self.partition = self.instantiate_partition(module, self.balance, self.group)
  File "/fs-examples/fairscale/nn/pipe/multiprocess_pipe.py", line 243, in instantiate_partition
    layers = module[first_layer : first_layer + num_layers]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 81, in __getitem__
    return self.__class__(OrderedDict(list(self._modules.items())[idx]))
TypeError: __init__() missing 6 required positional arguments: 'ninp', 'nhead', 'nhid', 'dropout', 'initrange', and 'ndecoder'

/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

HTH

**Comment by min-xu-ai** [comment]
wow, Thanks so much @vfdev-5!

@blefaudeux, those are related to zero?

**Comment by blefaudeux** [comment]
> wow, Thanks so much @vfdev-5!
> 
> @blefaudeux, those are related to zero?

it looks like it, but it's not from me actually, this has not been used for a very very long time.

**Comment by min-xu-ai** [comment]
perhaps we should just remove the part that is not working if not valuable.

**Comment by min-xu-ai** [comment]
Please merge with master. The CI issue you hit should be fixed now.

**Comment by vfdev-5** [comment]
@min-xu-ai looks like CI passed 🎉

**Comment by min-xu-ai** [comment]
I think this is safe enough to merge in. Sorry if it is not. @msbaines

**Pull request merged**
