### PR TITLE
Add method for disabling gradient checkpointing

### PR DESCRIPTION
**Pull request by timothybrooks**
## What does this PR do?
https://github.com/facebookresearch/fairscale/issues/771

## Before submitting

- [ ] Did you have fun?
  - Make sure you had fun coding 🙃
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [ ] N/A
- [ ] Did you write any new necessary tests?
  - [ ] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/master/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by anj-s** [comment]
@timothybrooks Thank you for the PR! It looks good. Can we add a small test for the change?

**Review by min-xu-ai — APPROVED** [review]
This looks great!

**Comment by anj-s** [comment]
@min-xu-ai  any reason we merged this into master without a unit test?

**Comment by min-xu-ai** [comment]
> @min-xu-ai any reason we merged this into master without a unit test?

Because there was no update for 7 days. I filed an issue to have the test separately. I think this allows for good forward momentum anyway. Let me know if you disagree.

**Comment by anj-s** [comment]
@min-xu-ai I think we should have a small unit test before merging into master since no one was blocked. I understand the case for momentum but I am more worried about breaking users. The past few days have been slow because of the long weekend. I know most people were OOO including me :)

**Comment by min-xu-ai** [comment]
Agreed about the risk of breaking users. However, this is a new API that is not used by anyone other than the author of the PR. All existing unit tests pass and new unit test were the only thing missing to cover the new API. So I don't really see the risk of breaking users in this case. That's why I thought it was very safe to merge.

**Pull request merged**
