### PR TITLE
[chore] Fix lint errors that broke master

### PR DESCRIPTION
**Pull request by anj-s**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [X ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes broken master: https://app.circleci.com/pipelines/github/facebookresearch/fairscale?branch=master

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by blefaudeux — APPROVED** [review]
LGTM, thanks Anjali !

**Review by min-xu-ai — APPROVED** [review]

**Review by msbaines — CHANGES_REQUESTED** [review]
I think the correct solution is to not include dataclasses in know_third_party.

**Comment by blefaudeux** [comment]
> I think the correct solution is to not include dataclasses in know_third_party.

linting used to be done with python3.6, [which does not have dataclasses](https://pypi.org/project/dataclasses/). Now if the reference python version changes ok, but it would be nice to publicized this a little

**Comment by blefaudeux** [comment]
> > I think the correct solution is to not include dataclasses in know_third_party.
> 
> linting used to be done with python3.6, [which does not have dataclasses](https://pypi.org/project/dataclasses/), which means that just following our contributing guide (like, setup pre-commit and such) would auto-add dataclasses to the dependencies. Now if the reference python version changes that's ok, but it would be nice to publicize this a little, this is the real change behind the breakage

looks like we changed the default to 3.7 sometime in the last month, updating my environments

**Comment by anj-s** [comment]
> I think the correct solution is to not include dataclasses in know_third_party.

Done.

**Review by blefaudeux — APPROVED** [review]
Thanks @anj-s !

**Pull request merged**
