### PR TITLE
Support multiple optimizers in ShardedDDP

### PR DESCRIPTION
**Pull request by SeanNaren**
## What does this PR do?

Modified ShardedDDP to support multiple OSS optimizers as input, as we have a few cases in lightning where multiple optimizers are required! cc @blefaudeux 

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by blefaudeux** [comment]
Ah it's interesting ! I'm changing this ShardedDDP a fair bit right now, to remove the manual .reduce() requirement for instance, one bug left to squash and I would create a PR, would your change be urgent or can it wait a couple of days ? In any case it would be great to add a unit test to make sure that this case is properly covered

**Comment by blefaudeux** [comment]
and thanks for the PR @SeanNaren !

**Comment by blefaudeux** [comment]
Ahh, I just saw that it was directly on the new branch, great ! Fine by me, and I like the Union[] typing, non breaking

**Comment by SeanNaren** [comment]
Thanks @blefaudeux :)

**Pull request merged**
