### PR TITLE
adding option wait_for_workers for DistributedPipeline

### PR DESCRIPTION
**Pull request by mrzzd**
This will allow for debug exceptions happening in any of workers.

### CODE REVIEW

**Comment by anj-s** [comment]
cc  @pbelevich  @SciPioneer

**Comment by min-xu-ai** [comment]
I am closing since this is not applicable. Please reopen if I am mistaken.

**Comment by anj-s** [comment]
> I am closing since this is not applicable. Please reopen if I am mistaken.

I wanted to cc the new owner of this work before closing it. I am going to reopen, cc the person and then close it.

**Comment by anj-s** [comment]
@pritamdamania87 @mrshenli @jamesr66a I wanted to highlight work that @mrzzd had completed in case it is relevant for the team. We are closing this PR for now.

**Pull request closed without merging**
