### PR TITLE
[benchmarks] Add benchmarks for FSDP

### PR DESCRIPTION
**Pull request by anj-s**
## What does this PR do?
This adds regression benchmarks for FSDP or FullyShardedDataParallel API. This is for running the vanilla case without any tuning. We will be relying on our full benchmarks suite to run all other cases. 

This is needed for SSD offload features for prevent regressions. Will be adding the SSD benchmark once the feature is checked in. 

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [ ] N/A
- [ ] Did you write any new necessary tests?
  - [ ] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/master/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by another-pjohnson** [comment]
We may be missing torchtext from requirements-test.txt after this change:

```
> python benchmarks/fsdp.py --debug --use_synthetic_data

Traceback (most recent call last):
  File "/data/users/johnsonpaul/github/fairscale/benchmarks/fsdp.py", line 15, in <module>
    from datasets.wikitext2_data import get_real_dataloaders as get_real_wikitext2_dataloaders
  File "/data/users/johnsonpaul/github/fairscale/benchmarks/datasets/wikitext2_data.py", line 13, in <module>
    import torchtext
ModuleNotFoundError: No module named 'torchtext'
```

**Comment by anj-s** [comment]
> We may be missing torchtext from requirements-test.txt after this change:
> 
> ```
> > python benchmarks/fsdp.py --debug --use_synthetic_data
> 
> Traceback (most recent call last):
>   File "/data/users/johnsonpaul/github/fairscale/benchmarks/fsdp.py", line 15, in <module>
>     from datasets.wikitext2_data import get_real_dataloaders as get_real_wikitext2_dataloaders
>   File "/data/users/johnsonpaul/github/fairscale/benchmarks/datasets/wikitext2_data.py", line 13, in <module>
>     import torchtext
> ModuleNotFoundError: No module named 'torchtext'
> ```

Ah I should have mentioned `requirements-benchmarks.txt` instead of `requirements-test.txt`. Thats why you saw this error. Let me know if you hit any other issues.

**Comment by min-xu-ai** [comment]
Is this still needed? @tmarkstrum's work is different from this?

**Comment by min-xu-ai** [comment]
A typo? @anj-s 

image

**Pull request merged**
