### PR TITLE
[chore] fix pyenv download cache

### PR DESCRIPTION
**Pull request by min-xu-ai**
## What does this PR do?
Fixes flakey test failures due to pyenv downloading.

## Before submitting

- [ ] Did you have fun?
  - Make sure you had fun coding 🙃
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/main/CONTRIBUTING.md)?
- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [ ] N/A
- [ ] Did you write any new necessary tests?
  - [ ] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/main/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by min-xu-ai** [comment]
This is ready for review. All tests are running here: https://app.circleci.com/pipelines/github/facebookresearch/fairscale/4227/workflows/a8905bb7-93f4-4319-af93-50ba319ee16e

I checked and caching should be working correctly now for pyenv.

**Comment by anupambhatnagar** [comment]
Is there a way to delete the cached pyenv in case it is buggy/stale?

**Comment by min-xu-ai** [comment]
> @min-xu-ai Is there a way to delete the cached pyenv in case it is buggy/stale?

I think cached file is not explicitly managed. In case an object is not desired, we just use v1/v2/v3 etc to switch to a new object.

**Comment by min-xu-ai** [comment]
merging this so that tests are less flaky. happy to address issues separately.

**Comment by anupambhatnagar** [comment]
> > @min-xu-ai Is there a way to delete the cached pyenv in case it is buggy/stale?
> 
> I think cached file is not explicitly managed. In case an object is not desired, we just use v1/v2/v3 etc to switch to a new object.

using v1/v2/v3 requires a code change in `.circleci/config.yml`. An alternative solution is to follow the convention as in here https://github.com/facebookresearch/fairscale/blob/main/.circleci/config.yml#L279 and set an environment variable for pyenv version in CircleCI. This will not require any code change and is non-blocking for users.

**Pull request merged**
