### PR TITLE
[feat] importing adascale and its test

### PR DESCRIPTION
**Pull request by min-xu-ai**
- imported from adaptdl repo
- no code changes, except formatting
- licence is apache 2.0

List of TODOs next:

- enable mypy
- add more tests if code cov is not 100%
- apply this to a project
- evolv the API; look into unifying LR schedule with this
- look into adaptive batch size DDP from adaptdl repo
- add doc and examples

testing: ran pytest

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by min-xu-ai** [comment]
abandoned

**Comment by stephenroller** [comment]
Just wondering, why abandoned? Did you get a chance to experiment with the optimizer at all?

**Comment by min-xu-ai** [comment]
Thanks Stephen. No, I haven't experimented with it. @msbaines mentioned that their license isn't compatible and since it is not too complex, we should rewrite (and also experiment) it. Therefore, it is abandoned and I will get a rewrite next week. (Next time, I should remember to attach a reason to abandoning)

**Comment by aurickq** [comment]
Hi, author of AdaptDL here. Could you let me know a bit more about the license incompatibility issue? It's certainly not our intent to be incompatible with BSD-3.

**Comment by min-xu-ai** [comment]
> Hi, author of AdaptDL here. Could you let me know a bit more about the license incompatibility issue? It's certainly not our intent to be incompatible with BSD-3.

Thank Aurick for reaching out! We will get back to you.

**Comment by Vittorio-Caggiano** [comment]
> Hi, author of AdaptDL here. Could you let me know a bit more about the license incompatibility issue? It's certainly not our intent to be incompatible with BSD-3.

Hi Aurick, one of the aim of fairscale it to be a playground to test technologies with the final goal to be included in pytorch. As such, we need to maintain compatibility with more permissive BSD-3 licenses.  Pytorch is very strict on this. We would love if you could Dual-license or re-license your code under BSD-3 and contribute it to fairscale.

**Comment by aurickq** [comment]
Thanks, @min-xu-ai and @Vittorio-Caggiano, we'll be happy to dual-license with BSD-3. Created an issue to track it over at the AdaptDL repo, hopefully will get around to finishing it some time this week.

**Comment by min-xu-ai** [comment]
@aurickq, maybe we should have a way to IM and coordinate off this PR? I think you can send a PR to this repo just like what this PR is doing after the license issue is resolved? That way, at least the authorship is kept in the git history. @Vittorio-Caggiano and @msbaines, what do you guys think?

**Comment by aurickq** [comment]
@min-xu-ai I'll be happy to chat over IM. Is the PyTorch slack workpace a good place?

**Comment by min-xu-ai** [comment]
@aurickq, cool, I don't have a slack account for pytorch yet. I just asked for an invite. Once I get that, we can connect there.

**Pull request closed without merging**
