### PR TITLE
Update requirements-dev.txt

### PR DESCRIPTION
**Pull request by tanujdhiman**
## What does this PR do?
Fixes # (issue). When I am installing requirements-dev.txt file it gives an error in `numpy` library

error

Rest of the dependencies are okay. No confliction.

Thanks
Tanuj

### CODE REVIEW

**Comment by anj-s** [comment]
@tanujdhiman It seems like you are not able to pull in the latest release of numpy as seen in [PyPI](https://pypi.org/project/numpy/#history). Can you try installing the latest version using == and seeing if that works. 

We have recently updated and standardized the package versions that we want to test on. I am not sure rolling back to 1.19 is the right way to go about this.

**Comment by tanujdhiman** [comment]
Hi @anj-s !!

Yes I've tried other versions too. like 1.21.1, 1.21.2, 1.21.3, 1.21.4 But here is the error!!
Then I think my pip is not upgraded for fetching the latest version then I upgraded my pip too. Again I am facing this error.

**Comment by min-xu-ai** [comment]
You are on windows, right? That's a different platform as we are testing.

**Comment by anupambhatnagar** [comment]
@tanujdhiman Can you share the exact platform name, platform version and pip version you are using? 

We conduct our testing on linux and at present there are no plans to support other platforms.

**Comment by tanujdhiman** [comment]
Thanks for replying !!

OS Platform - Windows
Pip - Latest

Thanks

**Comment by anupambhatnagar** [comment]
Closing the PR as we don't plan to roll back the numpy version to support windows.

**Pull request closed without merging**
