### PR TITLE
[chore] create v0.1.2

### PR DESCRIPTION
**Pull request by blefaudeux**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Bumps up the current fairscale version to 0.1.2 to include adascale improvements and huggingface-related fixes in ShardedDDP and OSS.

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.
cc @stas00 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by min-xu-ai — APPROVED** [review]
LGTM!

**Comment by min-xu-ai** [comment]
@blefaudeux it seems that the 0.1.2 release was made using the tag before this commit went it. The version number will be incorrect as a result? Did I miss anything?

**Comment by blefaudeux** [comment]
> @blefaudeux it seems that the 0.1.2 release was made using the tag before this commit went it. The version number will be incorrect as a result? Did I miss anything?

no your right, my bad, it was the first time I did that and missed this dependency.. the actual content is there though, I can create 0.1.3 (in the right order this time..) as a follow up if you think it's worth it ? Sorry a little busy with meetings today

**Comment by min-xu-ai** [comment]
sure. that'd be good with me.

**Pull request merged**
