### PR TITLE
[test] Add unittest for checkpoint & DDP

### PR DESCRIPTION
**Pull request by min-xu-ai**
- this change adds test cases to reproduce the error with checkpoint & DDP
- mandeep mentioned that there is also deadlock in this case, but this
  change doesn't cover that.
- we cover cases where weight sharing is OK
- however, same module multiple checkpoint or find_unused_parameters are
  both not OK

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by min-xu-ai** [comment]
BTW, I am see these mypy errors. But I checked that mypy version is the same as requirements-test.txt. Am I missing something?

```
$ mypy .
fairscale/nn/pipe/pipeline.py:29: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
fairscale/nn/pipe/pipeline.py:29: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
tests/nn/pipe_process/test_pipe.py:32: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
tests/nn/pipe_process/test_inplace.py:25: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
tests/nn/pipe_process/test_bugs.py:26: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
tests/nn/pipe_process/skip/test_leak.py:29: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
tests/nn/pipe_process/skip/test_gpipe.py:29: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
tests/nn/pipe_process/test_transparency.py:25: error: Cannot find implementation or library stub for module named 'tests.nn.model_parallel.commons'
Found 7 errors in 7 files (checked 81 source files)
```

**Comment by stephenroller** [comment]
(I got really excited and then saw this was on facebookresearch/fairscale and not facebookresearch/ParlAI)

**Comment by min-xu-ai** [comment]
> 
> 
> (I got really excited and then saw this was on facebookresearch/fairscale and not facebookresearch/ParlAI)

Sorry about that. I didn't know ParlAI cares about this too. Thanks for commenting on this. I will ask more info from you.

**Comment by stephenroller** [comment]
> Sorry about that. I didn't know ParlAI cares about this too. Thanks for commenting on this. I will ask more info from you.

Not needed, but thanks!

**Review by msbaines — COMMENTED** [review]
Thanks much for writing this. Maybe compute a norm of the grads to verify that the model gets the same grads in all cases. You will need to init the random seed in the beginning of the test.

**Comment by min-xu-ai** [comment]
> Thanks much for writing this. Maybe compute a norm of the grads to verify that the model gets the same grads in all cases. You will need to init the random seed in the beginning of the test.

Great idea. I have addressed this in the tests.

**Review by msbaines — APPROVED** [review]
LGTM. Thanks much!

**Pull request merged**
