### PR TITLE
[fix] Add the latest numpy version to requirements.txt

### PR DESCRIPTION
**Pull request by anj-s**
## What does this PR do?
Certain PRs (looks like forks) are running into mypy errors due to a bumped up numpy version that is being pulled in. 
* Bumped up numpy to >=1.21 as a temporary fix. We ideally don't want to have any other dependency other than PyTorch.
* Since np.append is untyped to begin with I did not see any fix other than adding an ignore. Maybe I am missing something? 
* I am still debugging how we are pulling in numpy 1.21 for PRs that are opened outside of the fairscale repo. PRs within the repo are using numpy 1.20. I tried invalidating the cache but that did not make a difference. PRs on different forks don't share a cache with the repo  according to [circleci](https://circleci.com/docs/2.0/caching/#caching-and-open-source). Maybe we want to consider that in the future.

## Before submitting

- [ ] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [ ] N/A
- [ ] Did you write any new necessary tests?
  - [x] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/master/CHANGELOG.md)? (if needed)
  - [x] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Review by min-xu-ai — APPROVED** [review]
LGTM

**Comment by omry** [comment]
More info:
numpy dropped Python 3.6 support in version 1.20.
As of now, fairseq still supports Python 3.6.

This diff makes Python 3.7 a hard requirement for fairscale, and thus for fairseq which depends on it.

Since the motivation here seems to be typing, I don't think it's worth changing the minimal supported Python version for fairseq and fairscale for it.

**Comment by min-xu-ai** [comment]
Thanks for the heads up, @omry! How about we add the requirement to requirements-test.txt? That should make our CI happy without require users to have newer numpy. @anj-s, what do you think?

**Comment by omry** [comment]
I get an uneasy feeling thinking that the CI will test on versions other than the official minimal versions.

**Comment by anj-s** [comment]
Thank you for the headsup @omry  As you can see in the PR description I am still debugging why some users ran into this. This was only a quick fix to unblock users.
@min-xu-ai  your suggestion sounds good. Opened a PR to make this change since we don't want to break fairseq.

**Comment by anj-s** [comment]
Merged [PR](https://github.com/facebookresearch/fairscale/pull/732). @omry  Let me know if this unblocks you. Thanks!

**Pull request merged**
